server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*.log
          host: ${HOSTNAME}
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{job="containerlogs"}'
          stages:
            - json:
                expressions:
                  output: log
            - regex:
                expression: '^(?P<timestamp>\S+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$'
                source: output
            - timestamp:
                source: timestamp
                format: RFC3339Nano
            - labels:
                stream:
                logtag:
  
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/**/*.log
          host: ${HOSTNAME}
