global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  - 'alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AI Orchestrator metrics
  - job_name: 'ai-orchestrator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ai-orchestrator:8000']
    scrape_interval: 15s

  # Node Exporter (for system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq:15692']

  # OpenSearch metrics
  - job_name: 'opensearch'
    metrics_path: '/_prometheus/metrics'
    static_configs:
      - targets: ['opensearch:9200']

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
