global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - '/etc/prometheus/alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ai-crews'
    static_configs:
      - targets: 
        - 'ai-orchestrator:8000'
        - 'ai-security:8001'
        - 'ai-monitoring:8002'
        - 'ai-deployment:8003'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AI Orchestrator metrics
  - job_name: 'ai-orchestrator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ai-orchestrator:8000']
    scrape_interval: 15s

  # Node Exporter (for system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq:15692']

  # OpenSearch metrics
  - job_name: 'opensearch'
    metrics_path: '/_prometheus/metrics'
    static_configs:
      - targets: ['opensearch:9200']

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
